### ISSUE TITLE
Current Status

### ISSUE THREAD

**Issue by avanderhoorn** [tunnelvisionlabs/dotnet-uritemplate#62]
Just wondering what the current status of the project is, etc?

**Comment by sharwell** [comment]
Hi @avanderhoorn and welcome to the project :smile: 

I'm fairly happy with the library right now, but I'm also the only person that's worked on it to date. I'd love to have another person give some feedback regarding its overall usability. If there are issues with the API, I'd like to work those out early so we can follow the strict [breaking changes policy](http://rackerlabs.github.io/dotnet-uritemplate/docs-latest/html/14557a8c-df73-468e-9b75-56e038b79f36.htm) starting with the 1.0 (stable) release.

**Comment by sharwell** [comment]
Hi @avanderhoorn,

As a quick update, I completed the work necessary to automatically build and test pull requests and the **master** branch. The project has moved from the rackerlabs organization to the tunnelvisionlabs organization, where development is able to proceed more quickly.

**Comment by avanderhoorn** [comment]
Thanks for the update. Will take a look and see what I can do!
